export const LATEST_NEWS_WIDGET = 1;
export const FAVOURITES_WIDGET = 2;
export const SERVICES_RECOMMENDATIONS_WIDGET = 3;
export const TRAINING_RECOMMENDATIONS_WIDGET = 4;
export const PUBLICATION_RECOMMENDATIONS_WIDGET = 5;
export const DATASET_RECOMMENDATIONS_WIDGET = 6;
export const SOFTWARE_RECOMMENDATIONS_WIDGET = 7;
